### ISSUE TITLE
Character & Table slightly in the ground

### ISSUE THREAD

**Issue by CapValGo** [EveronLife/EveronLife#109]
### What happened?

The Apple Traders' parts are under the terrain.

### What did you expect to happen?

All objects flat onto terrain.

### How can we reproduce it (as minimally and precisely as possible)?

Enter the workbench and load up DebugWorld.ent

### EveronLife Version

<details>

</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by CapValGo** [comment]
Additionally, the opposite is true for the Eden World, as floating, the character and table. The chair is still under the ground.

**Comment by Arkensor** [comment]
Yeah, these are just placeholders and this will fix itself in the near future when the core mechanics are in and everything is properly re-created from scratch. Moving them now would just cause merge conflicts. I'll leave the issue open so we do not accidentally forget about this in the debug world.

**Comment by thebonbon** [comment]
Fixed in https://github.com/EveronLife/EveronLife/pull/132

**Comment by Arkensor** [comment]
Yeah, and we will rebuild the main world once the early game farm routes are configured, so I'd consider this done.
