### ISSUE TITLE
Actions dont work on dropped items

### ISSUE THREAD

**Issue by thebonbon** [EveronLife/EveronLife#112]
### What happened?

Actions dont work on dropped items.

### What did you expect to happen?

Actions should still work on dropped items.

### How can we reproduce it (as minimally and precisely as possible)?

Drop any EveronLife item (apple, tomato, etc..) that doesn't have a collider on the ground and try to pick it up via action.

This only happens if there is no other collider near the item. E.g it works fine when the item is on a table.
_*None of the items currently has a collider._

### Anything else we need to know?

**Fix**: A proper collider should be added to every item.

### EveronLife Version

<details>
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by Arkensor** [comment]
Items usually do not have colliders yes, that is intended. Them not having a pickup interaction is odd.

**Comment by thebonbon** [comment]
> Items usually do not have colliders yes, that is intended.
>
Is it? Every item in the game has at least one collider.

**Comment by Tomboru** [comment]
Okay found an ez fix

**Comment by TL6868** [comment]
it is preferred to not have colliders on smaller items like an apple for example, you wouldn't want an apple left in the middle of the road to send your car flying

**Comment by 12gabriel3** [comment]
I am working on it. 
@TL6868 Colliders have different types of layers as far as im aware. Not every layer sends the car flying

**Comment by KasperOnPC** [comment]
> it is preferred to not have colliders on smaller items like an apple for example, you wouldn't want an apple left in the middle of the road to send your car flying

I wonder if there's an easy way we can have the colliders that aren't static and the apple would easily be smashed out of the way by a car tire? 

It does seem that they are 100% required for items to be picked up though unfortunatley.
