### ISSUE TITLE
Apple can't be Sold *Everon Map*

### ISSUE THREAD

**Issue by Tripit420** [EveronLife/EveronLife#148]
### What happened?

Trying to bring Functions to the Everon Map.
Gather Apple *works*
Sell Apple *Fails*

It's taking the Entity out of the Inventory, but it doesn't give M9 Ammo.

### What did you expect to happen?

Trade Apple -> Get M9 Ammo

### How can we reproduce it (as minimally and precisely as possible)?

 Pick up an Apple and try to sell Apple

### Anything else we need to know?

-

### EveronLife Version

<details>
0.0.12
</details>

### OS version

-

**Comment by Arkensor** [comment]
Known issue, a prototype system that will just be replaced.
