### ISSUE TITLE
Some prefabs do not inherit from Item_Base

### ISSUE THREAD

**Issue by Arkensor** [EveronLife/EveronLife#150]
### What happened?

These prefabs:
- Prefabs\Items\Drinks\WaterBottle.et
- Prefabs\Items\Food\Tomato.et
- Prefabs\Resources\Mining\* (all of them)
should all inherit from `Item_Base.et` so their own prefab data only adds additional information/changes instead of a full copy. This is probably my fault, cause I created them wrongly. Can somebody please go through all of them and fix this?

**Comment by thebonbon** [comment]
PR https://github.com/EveronLife/EveronLife/pull/155
