### ISSUE TITLE
Split EL_Utils into different more specific util files

### ISSUE THREAD

**Issue by thebonbon** [EveronLife/EveronLife#171]
### Summarize your proposed improvement

After https://github.com/EveronLife/EveronLife/pull/169 (Adds InventoryUtils) and https://github.com/EveronLife/EveronLife/pull/168 are merged:

Organize EL_Utils:
Things like GetStorageOwner should be part of InventoryUtils

---
From https://github.com/EveronLife/EveronLife/pull/168#discussion_r986031982

### Why is this needed?

Better organization

### Describe alternatives you've considered

-

### Add any other context or screenshots about the request here.

-

**Comment by Arkensor** [comment]
The idea was discussed and already taken into account int #168. We will split off more utils when ever needed.
