### ISSUE TITLE
Bug mod workshop

### ISSUE THREAD

**Issue by mecta02** [EveronLife/EveronLife#181]
### What happened?

When I run the scenario from the mode I have this
![image](https://user-images.githubusercontent.com/17672375/205485108-0228b6a1-8ea1-4030-9d4f-62bbb7385688.png)
![image](https://user-images.githubusercontent.com/17672375/205485401-8cafba19-7955-46d4-acb8-cfa23e55c017.png)

### What did you expect to happen?

to make it work

### How can we reproduce it (as minimally and precisely as possible)?

just do download the mode is by trying the scenario from this one

### EveronLife Version

<details>
0.0.13
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by Arkensor** [comment]
The mod is not yet updated for 0.9.7
We will do so in a few days.

**Comment by mecta02** [comment]
ok  thanks .an idea of the date please ;-(
