### ISSUE TITLE
 " SpawnPoint_LIFE.et "  missing from path 

### ISSUE THREAD

**Issue by GyldenDrage** [EveronLife/EveronLife#204]
### What happened?

Everon Life   > Prefabs > MP > Spawn > SpawnPoint_Life.et is missing from the filepath per the setup instructions

tried other spawn entities but keep spawning under water? 

Any other work around?

### What did you expect to happen?

add SpawnPoint_LIFE.et to world

### How can we reproduce it (as minimally and precisely as possible)?

download Everon Life on arma reforger mod manager

open a new world on 

### Anything else we need to know?

Only folders im seeing near that path are 

MP > Modes > Roleplay > then the GameModeRoleplay.et file

### EveronLife Version

<details>

0.0.14
</details>

### OS version

<details>

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
Edition	Windows 10 Home
Version	22H2
Installed on	‎2/‎18/‎2021
OS build	19045.2728
Experience	Windows Feature Experience Pack 120.2212.4190.0

```

</details>

**Comment by Arkensor** [comment]
Please load up the debug world and see the spawn point setup there. It is not a prefab currently, just a scripted entity.

**Comment by Pyth3rEx** [comment]
Can confirm I ran into the same issue, guess it needs to be fixed.

Credit to @Arkensor for the help when I had the issue:
![image](https://user-images.githubusercontent.com/26427764/231229400-d5da8a15-6890-48d2-af4b-0153cc5204bf.png)
