### ISSUE TITLE
Problems installing/using depencies

### ISSUE THREAD

**Issue by dukeluke** [EveronLife/EveronLife#208]
### What happened?

Hy.
I want to mention that the discord link on https://everon.life/ don't work so i am forced to write here.
I try go through your setting up server tutorial.(https://github.com/EveronLife/EveronLife/blob/main/docs/custom_server.md)
I always get stuck when I use the depency EveronLife. When I start Enfusion workbench with EnfusionLife I get a error message (can't Intialize game) message on the right bottom corner and I#m unable to start the world editor because it's greyed out.
Without EveronLife selected I can start World Editor.

On the last few lines in the console log I get this errors:

` SCRIPT       : Compiling Game scripts
  SCRIPT    (E): @"Scripts/Game/Feature/Character/Spawning/EL_RespawnHandlerComponent.c,39": Function 'OnPlayerDisconnected' is marked as override, but there is no function with this name in the base class
  SCRIPT    (E): @"Scripts/Game/Feature/Resources/EL_DestructibleResourceHitZone.c,20": Overloaded function 'ComputeEffectiveDamage' not compatible
  SCRIPT    (E): Can't compile "Game" script module!

Scripts/Game/Feature/Character/Spawning/EL_RespawnHandlerComponent.c(39): Function 'OnPlayerDisconnected' is marked as override, but there is no function with this name in the base class
  SCRIPT    (W): Failed to load
 PROFILING    : Compiling Game scripts took: 889.997100 ms
 ENGINE    (E): Unable to initialize a game/gamelib. Some workbench features will not work.
 SCRIPT    (W): Initializing default GameLib's game class.
 INIT         : Creating game instance(Game), version 0.9.8.64 built 2023-05-13 18:35:32 UTC.
 ENGINE       : Game successfully created.
 INIT         : Reload WB scripts
 PROFILING    : Reload WB scripts took: 10.990700 ms
 DEFAULT      : Using thumbnail cache directory: C:/Users/walke/AppData/Local/Temp/Enfusion/Projects/ReforgerLifeAustria/thumbnails
 DEFAULT      : Using autosave directory: C:/Users/walke/AppData/Local/Temp/Enfusion/Projects/ReforgerLifeAustria/autosaves
PROFILING    : Workbench startup took: 7938.441200 ms
`

### What did you expect to happen?

Using the world editor as described

### How can we reproduce it (as minimally and precisely as possible)?

Get through the setup server instruction until "Creating the world file"

### EveronLife Version

<details>
v.0.0.14
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
BuildNumber  Caption                   OSArchitecture  Version
22621        Microsoft Windows 11 Pro  64-Bit          10.0.22621

</details>

**Comment by Arkensor** [comment]
The mod is outdated on the workshop, we are working on a bigger update. The mod should be updated on the workshop this weekend.

**Comment by ThesiiNCey** [comment]
So is the update coming today?

**Comment by Arkensor** [comment]
Yeah if all things go well, an update should arrive later today :)
