### ISSUE TITLE
Cant Save player Data under Linux

### ISSUE THREAD

**Issue by ThesiiNCey** [EveronLife/EveronLife#210]
### What happened?

If i start my Server and play 2-3 minutes and i try to rejoin server is Crashing and i have test it under Windows and this is Working

### What did you expect to happen?

SCRIPT    (E): Failed to apply save-data 'EPF_CharacterSaveData:' to character.
Class:      'EL_RespawnSytemComponent'
Function: 'PrepareCharacter'

### How can we reproduce it (as minimally and precisely as possible)?

Start Server under Linux wit heveron Life mod the Saving is not working and get Overflow AABB Error

### EveronLife Version

<details>
</details>
Latest

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by Arkensor** [comment]
Hello,
thank you for the report. We have received a similar bug report already. We are investigating if this is something we need to fix or if it is an issue with the game on Linux. Can you please post the FULL script.log and crash.log for this?

**Comment by ThesiiNCey** [comment]
i used this via Pterodactyl

Here is the Egg

https://github.com/7Cav/service-level-configs/blob/develop/pterodactyl/eggs/arma/egg-reforger.json

**Comment by Arkensor** [comment]
And your logs?

**Comment by ThesiiNCey** [comment]
So tested With Clean Installed Server OS Debian 11.7

Vanilla Server Without Docker or everything

Mods

      {
        "modId": "5AAAC70D754245DD",
        "name": "Server Admin Tools",
        "version": "1.0.25"
      },
      {
        "modId": "59636E668EA37AD7",
        "name": "Everon Life",
        "version": "0.0.15"
      },
      {
        "modId": "5D6EA74A94173EDF",
        "name": "Enfusion Database Framework",
        "version": "0.1.0"
      },
      {
        "modId": "5D6EBC81EB1842EF",
        "name": "Enfusion Persistence Framework",
        "version": "0.1.0"
        
and after last line ( 23:41:24.829   PHYSICS   (W): Overflow in AABB, object removed from simulation ) is server Crashing

https://pastebin.com/wP32qBHh

**Comment by Arkensor** [comment]
Hello, I am happy to report that with https://github.com/Arkensor/EnfusionPersistenceFramework/commit/7685213d3108383b2543e94c453d063dc6ddedc6 this issue has been fixed. I will be updating the mods on the workshop later today or tomorrow, depending on when I can finish my documentation work for it.
