### ISSUE TITLE
SCR_InventoryMenuUI

### ISSUE THREAD

**Issue by platoathens** [EveronLife/EveronLife#211]
### What happened?

Error in modded SCR_InventoryMenuUI on line 277, project won't compile.

### What did you expect to happen?

Project should compile

### How can we reproduce it (as minimally and precisely as possible)?

Load project in workbench (latest from git)

### Anything else we need to know?

Replace m_pActiveStorageUI with m_pActiveStorageUI.Type()

### EveronLife Version

<details>
</details>

### OS version

<details>

```console
# On Linux:
$ cat /etc/os-release
# paste output here
$ uname -a
# paste output here

# On Windows:
C:\> wmic os get Caption, Version, BuildNumber, OSArchitecture
# paste output here
```

</details>

**Comment by Arkensor** [comment]
Missmatch of dependencies. Maybe I pushed something to early. Is theoretically already resolved with next update.
