### ISSUE TITLE
Resource Processing

### ISSUE THREAD

**Issue by PatchRequest** [EveronLife/EveronLife#4]
**Summarize your proposal**
Every life mod has a Resource processing System, therefore we need one too

**Describe the solution you'd like**
The goal is to have an interaction option that is generically defined.
It should take the "result" and the "input" resource as parameters to be reused for every processing interaction by just changing the parameters. 
The size of the reward, input, and the time to process should be parameters.
The Reward should be added to the player inventory directly.
The goal is to have an endless interaction but each x seconds a resource is processed for a smooth but scaling experience

**Describe alternatives you've considered**
There are multiple ways to implement the endless interaction.

**Comment by thebonbon** [comment]
Currently working on the direct system.

**Comment by KasperOnPC** [comment]
#107 was merged, and proposed changes include having multiple inputs and possibly outputs. 

I propose we might as well do a check inventory for items and check hand for items while we are at it. Much like was included in #101 and #102. This would allow for a tool to be required along with the processing prefab. Like needing a Shovel to process Concrete at a Cement Mixer for example.

**Comment by jasper-one** [comment]
The described version of this is already implemented, so will close out this issue and we can create a more advanced processor in the future or other changes can be proposed via other issues.
