### ISSUE TITLE
Add how-to on co-authors to the contributors guide

### ISSUE THREAD

**Issue by Arkensor** [EveronLife/EveronLife#58]
### Summarize your proposed improvement

The documentation should be updated to include links to guides on how to add co-authors to a commit. e.g. 

https://docs.github.com/en/enterprise-cloud@latest/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors

https://medium.com/blackode/creating-co-authored-commits-on-the-command-line-git-305ae2af9f73

### Why is this needed?

Only GitHub registered members that are associated with a merged commit in the repository are considered contributors. So if someone invested all their time into making concepts or models that someone else implemented and ported their contribution would not count. The person filing the PR should add those who helped significantly to one of the commits they are doing or make an extra one include them in the end if they themselves never pushed anything.

### Describe alternatives you've considered

People could be asked to each contribute at least something to be listed, but there are some work results that would never be included in the version control (e.g. design documents, discussion threads, etc).

**Comment by BenRauzi** [comment]
Happy to pick this up. Will get it written up today.

**Comment by MarvinVomberg** [comment]
@BenRauzi thanks for your interest in helping, you got any update on that?
