### ISSUE TITLE
Money System

### ISSUE THREAD

**Issue by PatchRequest** [EveronLife/EveronLife#9]
**Summarize your proposal**
A system to store the amount of money a player has

**Describe the solution you'd like**
A central system should hold the amount of money any player has at any given time
The system needs to provide multiple interfaces for server-driven and player-driven transactions
The Amount of money needs to be stored persistently 
If money should exist as real items or just a virtual number needs to be defined.

**Comment by LuxPoseidon** [comment]
Seeing what I can do with this, implementing it into my HUD UI.

https://github.com/LuxPoseidon/EveronLife

**Comment by LuxPoseidon** [comment]
> > Seeing what I can do with this, implementing it into my HUD UI. My implementation will be digital with no physical bills atm.
> > [LuxPoseidon/EveronLife](https://github.com/LuxPoseidon/EveronLife)
> 
> A physical item with quantity approach is worked on by me and @Jacob_Mango. But your code could be used for #34, couldn't it?

Absolutely, that’s what I picked up first, I am starting to implement the money portion just for testing the UI really, when you guys have a version where I can call into your code for values let me know and I’ll be happy to integrate it.

**Comment by Arkensor** [comment]
@LuxPoseidon I'll let you know. Will probably take 2-3 days.

**Comment by KasperOnPC** [comment]
@Arkensor let me know if you want me to have a go at compressing / implementing the models and textures.

**Comment by 12gabriel3** [comment]
# Physical money vs virtual money

## Reasoning
   In my opinion, illegal activities should be high reward but also high risk, with constant changes in power and hard to maintain. Easy to get into but hard to keep in place. In real life this comes with death and prison, but in the game, these systems do not work as a deterrent as much as they do IRL.
   Legal activities, on the other hand, are not as rewarding, but a great place if you are looking for stability and long term success.

## Solution
  If we make what you earn with illegal activities as easy to lose as it is to gain, while legal activities hard to gain but also hard to lose, it would solve that issue. You could choose the path of easy money but no future or you could choose the path of hard earned money and keep it protected.

## Proposal
Have 2 types of money:

### Virtual money
It is kept in your bank, where nobody can touch it. You can use it to pay for things anywhere, just like physical money. You receive paychecks in you bank account and receive money for sold legal items directly to your bank account.

### Physical money
It can be used anywhere just like virtual money, but you cannot deposit it. You receive this money for all illegal activities, including drug trafficking, illegal fishing, stolen cargo. If you die, you lose the items you are carrying, including physical money.

## Final thoughts
At the end of the day, it will be up to the server owner to decide. I think we should have the system in place to allow the server owner to choose:

- Which activities give physical money
- Which activities give virtual money (directly into the bank account)
- Whether you can turn physical money into virtual money or not

**Comment by PackJC** [comment]
Great ideas. 

I think physical money should be able to be deposited. There is no need to seperate the two in my opinion, but I like old school takistan life revolution. I agree with being paid for any item in physical form, jobs pay via bank account.

**Comment by PackJC** [comment]
> # Physical money vs virtual money
> ## Reasoning
> In my opinion, illegal activities should be high reward but also high risk, with constant changes in power and hard to maintain. Easy to get into but hard to keep in place. In real life this comes with death and prison, but in the game, these systems do not work as a deterrent as much as they do IRL. Legal activities, on the other hand, are not as rewarding, but a great place if you are looking for stability and long term success.
> 
> ## Solution
> If we make what you earn with illegal activities as easy to lose as it is to gain, while legal activities hard to gain but also hard to lose, it would solve that issue. You could choose the path of easy money but no future or you could choose the path of hard earned money and keep it protected.
> 
> ## Proposal
> Have 2 types of money:
> 
> ### Virtual money
> It is kept in your bank, where nobody can touch it. You can use it to pay for things anywhere, just like physical money. You receive paychecks in you bank account and receive money for sold legal items directly to your bank account.
> 
> ### Physical money
> It can be used anywhere just like virtual money, but you cannot deposit it. You receive this money for all illegal activities, including drug trafficking, illegal fishing, stolen cargo. If you die, you lose the items you are carrying, including physical money.
> 
> ## Final thoughts
> At the end of the day, it will be up to the server owner to decide. I think we should have the system in place to allow the server owner to choose:
> 
> * Which activities give physical money
> * Which activities give virtual money (directly into the bank account)
> * Whether you can turn physical money into virtual money or not


Great ideas.

I think physical money should be able to be deposited. There is no need to seperate the two in my opinion, but I like old school takistan life revolution. I agree with being paid for any item in physical form, jobs pay via bank account.

**Comment by LuxPoseidon** [comment]
Yea don't think of them as separate things, just allow physical item when its on a player as an option to server owners.

**Comment by 12gabriel3** [comment]
I think if we have this distinction of virtual and physical money, while making vendors accept both, it would be hard to make them a server setting. 
One server might choose to only deal with virtual money. 
Another can choose to make all activities pay with physical money and you have to deposit.
Another can choose to make so that legal activities pay with virtual money while illegal activities pay with physical money and you cant deposit it.

**Comment by MrColeSlaw** [comment]
> I think if we have this distinction of virtual and physical money, while making vendors accept both, it would not be hard to make them a server setting. One server might choose to only deal with virtual money. Another can choose to make all activities pay with physical money and you have to deposit. Another can choose to make so that legal activities pay with virtual money while illegal activities pay with physical money and you cant deposit it.

Why not have "dirty" physical money that has to be cleaned before it can be deposited, I think that provides the most flexibility as you could limit the dirty money to specific "seedy" vendors, and clean physical money can be used everywhere and deposited. Also, the existence of a money laundering place allows for interesting post situation (i.e bank heist) roleplay, as the police would have places to stake out, this fulfills the increase in risk in your original proposal.

**Comment by thebonbon** [comment]
I think every activity should give physical money. You can deposit / withdraw or pay a trader directly from your bank (virtual).

> Why not have "dirty" physical money that has to be cleaned before it can be deposited,
>
I also really like this idea. Keeps all the money physical but makes illegal activities harder. So you cant just rob a bank and put all the money directly in your bank account while you are there.

**Comment by PackJC** [comment]
@thebonbon traditionally in the past life mods you could not deposit money ~X minutes after robbing gas station or bank.

**Comment by MrColeSlaw** [comment]
> @thebonbon traditionally in the past life mods you could not deposit money ~X minutes after robbing gas station or bank.

The A3 framework I used to play on had a dirty money system like I proposed, I think that's better than a straight timer, you could always sit in a random building and wait it out, whereas a dirty money system means you're likely to butt heads with cops . Nothing inherently wrong with a straight timer, I just think it's not as "immersive"
